### ISSUE TITLE
Support checking projects which do not have "module name" in their github path

### ISSUE THREAD

**Issue by devinsba** [openzipkin-contrib/apache-release-verification#13]
When we migrate the `zipkin` project into the Apache repo, it will be located at: `https://github.com/apache/incubator-zipkin.git`, the code as it exists now would look for it at: `https://github.com/apache/incubator-zipkin-zipkin.git`

**Comment by devinsba** [comment]
To a lesser extent this affects our ability to check projects outside of zipkin also, ones that do not have modules at all, where their git repo will be hosted like the `zipkin` one, and their release path will be `https://dist.apache.org/repos/dist/dev/incubator/${projectName}/${version}/` instead of `https://dist.apache.org/repos/dist/dev/incubator/${projectName}/${moduleName}/${version}/`

**Comment by abesto** [comment]
Nice one. My first idea for approaching this is making `--module` optional, and dropping that part of the URL path if not provided.
