### ISSUE TITLE
Verification tool doesn't allow anonymous cloning and the git repo name seems wrong

### ISSUE THREAD

**Issue by zeagord** [openzipkin-contrib/apache-release-verification#30]
Need to enter username and password for anonymous cloning and the repo name is slightly odd.

Please see the logs below

```
Executing `git clone https://github.com/apache/incubator-zipkin-zipkin.git /tmp/tmpm3rcq1kv/git/incubator-zipkin-zipkin.git`
Cloning into '/tmp/tmpm3rcq1kv/git/incubator-zipkin-zipkin.git'...
Username for 'https://github.com': 
```

**Comment by abesto** [comment]
Yesir. There are some rough edges around the repo name generation (#23 kinda sorta tracks handling this better). Asking for the user-name is a side-effect of trying to a wrong repo. Here's an incantation to make this go for now:

```
python src/main.py --module zipkin --version 2.13.0 --gpg-key DA805D02 \
      --git-hash 7c08091d3f8b0428d1d78839d3bef0f6887746f2 --repo dev \
      --zipname-template 'apache-{module}{dash_incubating}-{version}-source-release' \
      --github-reponame-template '{incubator_dash}{module}.git'
```

The build-and-test phase takes quite a while, and outputs much text. We can discuss how best to handle this over time; for now, you can disable it by also passing in `--build-and-test-command 'echo skipped'`.

Note also that the checks `No .gitignore-d files in source archive` and `No binary files in the release` are failing, with at least the latter one being a false positive (it lists `.json` files which are obviously non-binary, and `.ico`, which is not a problem, so this check needs to be refined; tracking in #31, downgraded from `FAIL` to `NOTE` level for now).

**Comment by abesto** [comment]
`No .gitignore-d files in source archive` after reproducing manually finds `zipkin/dependency-reduced-pom.xml`, which is in `.gitignore`, but is in the source archive. This might be fine, and also it's not outputting what it should, so disabled for now, opened #32 to track.

**Comment by abesto** [comment]
#35 will make this significantly less confusing.

Closing to keep the open issue list clean (correct behavior can be achieved with some gymnastics, and remote configs will remove the need for that)
