### ISSUE TITLE
Ignore .github directory

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin-contrib/apache-release-verification#36]
currently we fail like this. We should not require .github in the source dist

```
[FAIL] Git tree at provided revision matches source archive
/tmp/tmppa_5v1dw/git/incubator-zipkin/.github is only in the git checkout
See above for a full output of diff.
```

**Comment by abesto** [comment]
That's weird, https://github.com/openzipkin-contrib/apache-release-verification/commit/b51359fa2857c91302e18411a8e2745d8dfad921 should fix that (from ~2 weeks ago). How exactly did you invoke the tool?

**Comment by shakuzen** [comment]
> That's weird, [b51359f](https://github.com/openzipkin-contrib/apache-release-verification/commit/b51359fa2857c91302e18411a8e2745d8dfad921) should fix that (from ~2 weeks ago).

@adriancole assuming you were using the docker command, did you `docker pull abesto/openzipkin-contrib-apache-release-verification` before running it to make sure you have the latest image?

**Comment by abesto** [comment]
I'm gonna assume this was a case of an outdated checker version and close, please re-open if the issue persists.
