### ISSUE TITLE
LICENSE can have addendums

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin-contrib/apache-release-verification#37]
We were required to make addendums to the LICENSE file, which trips the verification tool like this. One possible way out is to look that the file starts with the stock LICENSE text as opposed to exactly equals.

```
[FAIL] LICENSE is Apache 2.0
Executing `diff /tmp/tmppa_5v1dw/expected_license /tmp/tmppa_5v1dw/unzipped/zipkin-2.14.0/LICENSE` exited with non-zero status code 1. See above for output. (Note that the command was run under `set -euo pipefail`)
```

**Comment by codefromthecrypt** [comment]
here's an example of such https://github.com/apache/incubator-zipkin-dependencies/pull/138

**Comment by abesto** [comment]
Yeah this check is pretty fragile, and can be made infinitely complex :D I'll put up a PR to fix this case, pragmatic approach here I think is extending it just enough to support cases we care about on a case-by-case basis.
