### ISSUE TITLE
sha512sum might not exist (many things might not until dockerized)

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin-contrib/apache-release-verification#5]
My verification failed in the script due to missing `sha512sum`. However, it passes when using normal `shasum`.

**Comment by codefromthecrypt** [comment]
if we have python anyway, maybe we can use hashlib?

**Comment by codefromthecrypt** [comment]
`brew install coreutils`

**Comment by shakuzen** [comment]
I ran into missing `sha512sum` also. My macbook is pretty new and actually it doesn't even have `wget` either.

**Comment by abesto** [comment]
Yep, this is why we'll need the Docker env.

> if we have python anyway, maybe we can use hashlib?

I want to do as much as we can by shelling out to make the commands reproducible. That is: after the run, if you want to go and double-check something, you can start by copy-pasting the command.

In the case of macOS and `sha512sum`, if you don't want to set confuse other software by putting GNU binaries on your `$PATH`, I think the default is that they're available with a `g` prefix; that is, `gsha512sum`.

**Comment by codefromthecrypt** [comment]
> I want to do as much as we can by shelling out to make the commands
reproducible. That is: after the run, if you want to go and double-check
something, you can start by copy-pasting the command.

interesting thanks for sharing rationale!



> In the case of macOS and sha512sum, if you don't want to set confuse
> other software by putting GNU binaries on your $PATH, I think the default
> is that they're available with a g prefix; that is, gsha512sum.
>
latest from homebrew seems to just make it so anyway :P

**Comment by drolando** [comment]
> I want to do as much as we can by shelling out to make the commands reproducible. That is: after the run, if you want to go and double-check something, you can start by copy-pasting the command.

shell commands also don't behave exactly the same way on macos and linux, which might make them pass on one and fail on the other causing confusion. I think your PR to run them in a docker container is the right way to go.

**Comment by abesto** [comment]
Docker stuff is in, closing this :fireworks:
